In [12]:
import pandas as pd
import numpy as np

In [2]:
accidents = pd.read_csv('../data/accidents.csv')
casualties = pd.read_csv('../data/casualties.csv', on_bad_lines = 'skip')
vehicles = pd.read_csv('../data/vehicles.csv', on_bad_lines = 'skip')

In [3]:
main_df = accidents.merge(casualties).merge(vehicles)

## Remove columns with lots or few unique values

In [18]:
for i in range(main_df.shape[1]):
    unique_vals = len(np.unique(main_df[main_df.columns[i]].astype('str')))
    percentage = unique_vals/main_df.shape[0]
    print(f'{main_df.columns[i]}: {unique_vals}, {percentage*100}%')

Accident_Index: 1640597, 74.0101140423689%
Location_Easting_OSGR: 182959, 8.253590891046231%
Location_Northing_OSGR: 223555, 10.084945324623769%
Longitude: 1148132, 51.79418239561153%
Latitude: 1081780, 48.800931105417014%
Police_Force: 51, 0.0023006965245948967%
Accident_Severity: 3, 0.00013533508968205276%
Number_of_Vehicles: 27, 0.001218015807138475%
Number_of_Casualties: 50, 0.002255584828034213%
Date: 3652, 0.1647479158396189%
Day_of_Week: 7, 0.0003157818759247898%
Time: 1440, 0.06496084304738532%
Local_Authority_(District): 416, 0.01876646576924465%
Local_Authority_(Highway): 207, 0.00933812118806164%
1st_Road_Class: 6, 0.0002706701793641055%
1st_Road_Number: 6988, 0.3152405355660616%
Road_Type: 6, 0.0002706701793641055%
Speed_limit: 8, 0.00036089357248547405%
Junction_Detail: 10, 0.0004511169656068425%
Junction_Control: 6, 0.0002706701793641055%
2nd_Road_Class: 7, 0.0003157818759247898%
2nd_Road_Number: 7382, 0.3330145440109712%
Pedestrian_Crossing-Human_Control: 4, 0.00018044678624273703%
Pedestrian_Crossing-Physical_Facilities: 7, 0.0003157818759247898%
Light_Conditions: 5, 0.00022555848280342126%
Weather_Conditions: 10, 0.0004511169656068425%
Road_Surface_Conditions: 6, 0.0002706701793641055%
Special_Conditions_at_Site: 9, 0.00040600526904615826%
Carriageway_Hazards: 7, 0.0003157818759247898%
Urban_or_Rural_Area: 3, 0.00013533508968205276%
Did_Police_Officer_Attend_Scene_of_Accident: 4, 0.00018044678624273703%
LSOA_of_Accident_Location: 35465, 1.599886318524667%
Vehicle_Reference: 67, 0.003022483669565845%
Casualty_Reference: 97, 0.004375834566386373%
Casualty_Class: 3, 0.00013533508968205276%
Sex_of_Casualty: 3, 0.00013533508968205276%
Age_of_Casualty: 105, 0.004736728138871847%
Age_Band_of_Casualty: 12, 0.000541340358728211%
Casualty_Severity: 3, 0.00013533508968205276%
Pedestrian_Location: 12, 0.000541340358728211%
Pedestrian_Movement: 11, 0.0004962286621675268%
Car_Passenger: 4, 0.00018044678624273703%
Bus_or_Coach_Passenger: 6, 0.0002706701793641055%
Pedestrian_Road_Maintenance_Worker: 4, 0.00018044678624273703%
Casualty_Type: 21, 0.0009473456277743694%
Casualty_Home_Area_Type: 4, 0.00018044678624273703%
Vehicle_Type: 21, 0.0009473456277743694%
Towing_and_Articulation: 7, 0.0003157818759247898%
Vehicle_Manoeuvre: 19, 0.0008571222346530009%
Vehicle_Location-Restricted_Lane: 11, 0.0004962286621675268%
Junction_Location: 10, 0.0004511169656068425%
Skidding_and_Overturning: 7, 0.0003157818759247898%
Hit_Object_in_Carriageway: 13, 0.0005864520552888953%
Vehicle_Leaving_Carriageway: 10, 0.0004511169656068425%
Hit_Object_off_Carriageway: 13, 0.0005864520552888953%
1st_Point_of_Impact: 6, 0.0002706701793641055%
Was_Vehicle_Left_Hand_Drive?: 3, 0.00013533508968205276%
Journey_Purpose_of_Driver: 8, 0.00036089357248547405%
Sex_of_Driver: 4, 0.00018044678624273703%
Age_of_Driver: 101, 0.00455628135262911%
Age_Band_of_Driver: 12, 0.000541340358728211%
Engine_Capacity_(CC): 2310, 0.10420801905518062%
Propulsion_Code: 12, 0.000541340358728211%
Age_of_Vehicle: 87, 0.00392471760077953%
Driver_IMD_Decile: 11, 0.0004962286621675268%
Driver_Home_Area_Type: 4, 0.00018044678624273703%

In [20]:
main_df.head()

,Accident_Index,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,...,Was_Vehicle_Left_Hand_Drive?,Journey_Purpose_of_Driver,Sex_of_Driver,Age_of_Driver,Age_Band_of_Driver,Engine_Capacity_(CC),Propulsion_Code,Age_of_Vehicle,Driver_IMD_Decile,Driver_Home_Area_Type
0,200501BS00001,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,...,1,15,2,74,10,-1,-1,-1,7,1
1,200501BS00002,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,...,1,1,1,42,7,8268,2,3,-1,-1
2,200501BS00003,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,...,1,15,1,62,9,1762,1,6,1,1
3,200501BS00004,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,...,1,15,2,49,8,1769,1,4,2,1
4,200501BS00005,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,...,1,15,1,49,8,85,1,10,-1,-1

In [ ]:
['Accident_Index', 'Location_Easting_OSGR', 'Location_Northing_OSGR', 'Longitude', 'Latitude', 'Day_of_Week']

Date przetworzyć